// <auto-generated />
namespace Infrastrucutre.Core.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Category_FK_item_category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Category_FK_item_category));
        
        string IMigrationMetadata.Id
        {
            get { return "201404020922346_Category_FK_item_category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
