// <auto-generated />
namespace Infrastrucutre.Core.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FK_item_supplier : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FK_item_supplier));
        
        string IMigrationMetadata.Id
        {
            get { return "201404020910520_FK_item_supplier"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
